name: llama
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - comm=0.2.2
  - debugpy=1.6.7
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - ipykernel=6.29.5
  - ipython=8.27.0
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=3.0.15
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.11.9
  - python-dateutil=2.9.0
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==0.34.2
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.8
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.6.0
      - appdirs==1.4.4
      - attrs==24.2.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.44.1
      - black==24.8.0
      - blobfile==3.0.0
      - boltons==21.0.0
      - bracex==2.5.post1
      - brotli==1.1.0
      - cachetools==5.5.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - click-option-group==0.5.6
      - codeshield==1.0.1
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - contourpy==1.3.0
      - cryptography==43.0.1
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - datasets==3.0.1
      - deepdiff==8.0.1
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - dill==0.3.8
      - distro==1.9.0
      - effdet==0.4.1
      - emoji==2.13.2
      - evaluate==0.4.3
      - face==22.0.0
      - fairscale==0.4.13
      - filelock==3.16.1
      - filetype==1.2.0
      - fire==0.6.0
      - flatbuffers==24.3.25
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - glom==22.1.0
      - google-api-core==2.20.0
      - google-auth==2.35.0
      - google-cloud-vision==3.7.4
      - googleapis-common-protos==1.65.0
      - grpcio==1.66.2
      - grpcio-status==1.62.3
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.2
      - huggingface-hub==0.25.1
      - humanfriendly==10.0
      - idna==3.10
      - importlib-metadata==7.1.0
      - inflate64==1.0.0
      - iopath==0.1.10
      - ipywidgets==8.1.5
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonpath-python==1.0.6
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - langdetect==1.0.9
      - layoutparser==0.3.4
      - llama-models==0.0.36
      - llama-recipes==0.0.4.post1
      - llama-toolchain==0.0.35
      - loralib==0.1.2
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.22.0
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - multivolumefile==0.2.3
      - mypy-extensions==1.0.0
      - networkx==3.3
      - nltk==3.9.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.68
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - onnx==1.16.2
      - onnxruntime==1.19.2
      - openai==1.38.0
      - opencv-python==4.10.0.84
      - opentelemetry-api==1.25.0
      - opentelemetry-exporter-otlp-proto-common==1.25.0
      - opentelemetry-exporter-otlp-proto-http==1.25.0
      - opentelemetry-instrumentation==0.46b0
      - opentelemetry-instrumentation-requests==0.46b0
      - opentelemetry-proto==1.25.0
      - opentelemetry-sdk==1.25.0
      - opentelemetry-semantic-conventions==0.46b0
      - opentelemetry-util-http==0.46b0
      - optimum==1.17.1
      - orderly-set==5.2.2
      - pandas==2.2.3
      - pathspec==0.12.1
      - pdf2image==1.17.0
      - pdfminer-six==20231228
      - pdfplumber==0.11.4
      - peewee==3.17.6
      - peft==0.13.0
      - pi-heif==0.18.0
      - pikepdf==9.3.0
      - pillow==10.4.0
      - portalocker==2.10.1
      - proto-plus==1.24.0
      - protobuf==4.25.5
      - py7zr==0.22.0
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybcj==1.0.2
      - pycocotools==2.0.8
      - pycparser==2.22
      - pycryptodomex==3.20.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pyparsing==3.1.4
      - pypdf==5.0.1
      - pypdfium2==4.30.0
      - pyppmd==1.1.0
      - python-dotenv==1.0.1
      - python-iso639==2024.4.27
      - python-magic==0.4.27
      - python-multipart==0.0.12
      - pytz==2024.2
      - pyyaml==6.0.1
      - pyzstd==0.16.1
      - rapidfuzz==3.10.0
      - referencing==0.35.1
      - regex==2024.9.11
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.5.3
      - rouge-score==0.1.2
      - rpds-py==0.20.0
      - rsa==4.9
      - ruamel-yaml==0.17.40
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - semgrep==1.90.0
      - sentence-transformers==3.1.1
      - sentencepiece==0.2.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - sympy==1.13.3
      - tabulate==0.9.0
      - termcolor==2.4.0
      - texttable==1.7.0
      - threadpoolctl==3.5.0
      - tiktoken==0.7.0
      - timm==1.0.9
      - tokenize-rt==6.0.0
      - tokenizers==0.20.0
      - tomli==2.0.1
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.66.5
      - transformers==4.45.1
      - triton==3.0.0
      - typing-extensions==4.8.0
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - unstructured==0.15.8
      - unstructured-client==0.25.9
      - unstructured-inference==0.7.36
      - unstructured-pytesseract==0.3.13
      - urllib3==2.2.3
      - wcmatch==8.5.2
      - widgetsnbextension==4.0.13
      - wrapt==1.16.0
      - xxhash==3.5.0
      - yarl==1.13.1
      - ml_dtypes==0.2.0
      - gast==0.6.0
      - astunparse==1.6.3
      - opt-einsum==3.4.0
# prefix: /home/saner/miniconda3/envs/llama
